using BIS.ERP.Data;
using BIS.ERP.Models;
using Microsoft.EntityFrameworkCore;

namespace BIS.ERP.Services
{
    public class UserAccessService
    {
        private readonly AppDbContext _context;

        public UserAccessService(AppDbContext context)
        {
            _context = context;
        }

        public async Task EnsureSchemaAsync()
        {
            await _context.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""Users"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Login"" varchar(80) NOT NULL,
                    ""Email"" varchar(160) NOT NULL DEFAULT '',
                    ""PasswordHash"" text NOT NULL,
                    ""FullName"" varchar(200) NOT NULL DEFAULT '',
                    ""Role"" integer NOT NULL DEFAULT 0,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""IsActive"" boolean NOT NULL DEFAULT true,
                    ""LastLoginDate"" timestamp with time zone NULL,
                    ""LastInfoBaseId"" uuid NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_Login"" ON ""Users"" (""Login"");

                CREATE TABLE IF NOT EXISTS ""UserAccessPermissions"" (
                    ""Id"" uuid PRIMARY KEY,
                    ""UserId"" integer NOT NULL,
                    ""NavigationKey"" varchar(160) NOT NULL,
                    ""IsAllowed"" boolean NOT NULL DEFAULT true,
                    ""UpdatedAt"" timestamp with time zone NOT NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_UserAccessPermissions_User_Key""
                    ON ""UserAccessPermissions"" (""UserId"", ""NavigationKey"");
            ");

            await SeedUserAsync("admin", "admin", "Администратор", "admin@local", UserRole.Admin);
            await SeedUserAsync("user", "user", "Пользователь", "user@local", UserRole.User);
        }

        public async Task<List<User>> GetUsersAsync()
        {
            await EnsureSchemaAsync();
            return await _context.Users.AsNoTracking()
                .OrderByDescending(user => user.Role)
                .ThenBy(user => user.Login)
                .ToListAsync();
        }

        public async Task<HashSet<string>> GetAllowedKeysAsync(int userId)
        {
            await EnsureSchemaAsync();
            var keys = await _context.UserAccessPermissions.AsNoTracking()
                .Where(permission => permission.UserId == userId && permission.IsAllowed)
                .Select(permission => permission.NavigationKey)
                .ToListAsync();
            return keys.ToHashSet(StringComparer.OrdinalIgnoreCase);
        }

        public async Task SavePermissionsAsync(int userId, IEnumerable<string> allowedKeys)
        {
            await EnsureSchemaAsync();
            var user = await _context.Users.FindAsync(userId)
                ?? throw new InvalidOperationException("Пользователь не найден.");
            if (user.Role == UserRole.Admin)
                throw new InvalidOperationException("Администратор всегда имеет полный доступ.");

            var oldPermissions = await _context.UserAccessPermissions
                .Where(permission => permission.UserId == userId)
                .ToListAsync();
            _context.UserAccessPermissions.RemoveRange(oldPermissions);

            var permissions = allowedKeys
                .Where(key => !string.IsNullOrWhiteSpace(key))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .Select(key => new UserAccessPermission
                {
                    UserId = userId,
                    NavigationKey = key,
                    IsAllowed = true,
                    UpdatedAt = DateTime.UtcNow
                });
            await _context.UserAccessPermissions.AddRangeAsync(permissions);
            await _context.SaveChangesAsync();
        }

        private async Task SeedUserAsync(string login, string password, string fullName, string email, UserRole role)
        {
            if (await _context.Users.AnyAsync(user => user.Login == login))
                return;

            await _context.Users.AddAsync(new User
            {
                Login = login,
                FullName = fullName,
                Email = email,
                PasswordHash = global::BCrypt.Net.BCrypt.HashPassword(password),
                Role = role,
                IsActive = true,
                CreatedAt = DateTime.UtcNow
            });
            await _context.SaveChangesAsync();
        }
    }
}
